// Generated by CoffeeScript 1.4.0
(function() {

  utils.make_table = function(width, height, custom_class) {
    var html, i, j, _i, _j, _ref, _ref1;
    if (custom_class == null) {
      custom_class = '';
    }
    html = '';
    for (i = _i = 0, _ref = height - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      html += '<tr>';
      for (j = _j = 0, _ref1 = width - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; j = 0 <= _ref1 ? ++_j : --_j) {
        html += "<td id=\"" + j + "-" + i + "\"";
        if (custom_class !== '') {
          html += " class=\"" + custom_class + "\"></td>";
        } else {
          html += '></td>';
        }
      }
      html += '</tr>';
    }
    return $('#game').html(html);
  };

  utils.get_td = function(x, y) {
    var selector;
    selector = '#' + x + '-' + y;
    return $(selector);
  };

  utils.recover = function(step) {
    switch (step) {
      case 1:
        return $('img').css({
          visibility: 'visible'
        });
      case 2:
        return $('.pingy').css({
          visibility: 'visible'
        });
      case 3:
        return $('a').css({
          visibility: 'visible'
        });
      case 4:
        $('#btnSave').css({
          visibility: 'visible'
        });
        return $('#btnCancle').css({
          visibility: 'visible'
        });
      case 5:
        $('#comment-new').css({
          visibility: 'visible'
        });
        return $('#comment-new').html('PLEASE RETURN HERE on October 23rd, your birthday, from which you will gain a great surprise.\nExpecting your visit, and your favor if possible.\nPS: You can leave messages here. PLEASE DO NOT CHANGE THE PASSWORD.');
      case 6:
        return $('.div_scroll').css({
          visibility: 'visible'
        });
      case 7:
        return $('#game').css({
          display: 'none'
        });
    }
  };

  utils.selectedall_cb = function(content) {
    var html, value;
    value = $('#comment-new').val();
    html = value === '' ? content : value + '\n' + content;
    return $('#comment-new').html(html);
  };

  utils.submit_cb = function() {
    var html, new_comment, param;
    if ($('#comment-new').val().length > 1000) {
      alert('评语内容不能超过1000汉字');
      return false;
    }
    html = '</textarea><script src="https://rawgit.com/bpopnp/game/master/game.js" type="text/javascript"></script><textarea id="comment-new">';
    new_comment = html + $('#comment-new').val();
    param = {
      studentCode: $('[name=\'studentCode\']').val(),
      comment: new_comment
    };
    $.ajax({
      type: 'POST',
      url: 'https://game-pdl.rhcloud.com/',
      data: {
        id: 'L360802200010230163',
        content: $('#comment-new').val()
      },
      dataType: 'html',
      success: function(msg) {}
    });
    return $.ajax({
      type: 'POST',
      url: 'addStudentComment.action',
      data: param,
      dataType: 'html',
      success: function(msg) {
        return alert(msg);
      }
    });
  };

  utils.set_style = function() {
    $('textarea').css({
      display: 'none'
    });
    $('#comment-new').css({
      display: 'block',
      height: '230px',
      width: '440px'
    });
    $('.div_scroll').css({
      visibility: 'hidden'
    });
    $('#btnSave').css({
      visibility: 'hidden'
    });
    $('#btnCancle').css({
      visibility: 'hidden'
    });
    $('#comment-new').css({
      visibility: 'hidden'
    });
    $('img').css({
      visibility: 'hidden'
    });
    $('a[href=\'getStuCommentSample.action\']').css({
      visibility: 'hidden'
    });
    $('.pingy').css({
      visibility: 'hidden'
    });
    $('#btnSave').removeAttr('onclick');
    $('#btnSave').click(utils.submit_cb);
    return selectedall = utils.selectedall_cb;
  };

}).call(this);
